version: 2

python:
  version: "3.9"  # Wersja Pythona 3.11
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py  # Ścieżka do pliku conf.py

formats: ['htmlzip']


