version: "2"
build:
  os: "ubuntu-22.04"
  tools:
    python:
      version: "3.9"
      install:
        - pip install -r docs/requirements.txt

sphinx:
  configuration: "docs/source/conf.py"
  formats:
    - 'htmlzip'



